const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const modal=$('#offerModal'), confirmation=$('#confirmation'), menu=$('.nav'), toggle=$('.menu-toggle');
function openModal(m){m.classList.add('show');m.setAttribute('aria-hidden','false')}function closeModal(m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}
setTimeout(()=>{if(!sessionStorage.getItem('offerSeen')){openModal(modal);sessionStorage.setItem('offerSeen','1')}},1400);
$('.modal-close').addEventListener('click',e=>closeModal(e.target.closest('.modal'))); $$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m)}));$$('[data-close-modal]').forEach(x=>x.addEventListener('click',()=>closeModal(modal)));
toggle.addEventListener('click',()=>{menu.classList.toggle('open');toggle.setAttribute('aria-expanded',menu.classList.contains('open'))});$$('.nav a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));
const date=$('#date'),time=$('#time'),service=$('#service'),barber=$('#barber'),name=$('#name'),phone=$('#phone'),email=$('#email');
const prices={'Signature Cut':220,'Skin Fade':250,'Beard Sculpt':150,'Cut + Beard':340,'Kids Cut':160,'Head Shave':180};
const slots=['09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00','17:00'];slots.forEach(t=>time.insertAdjacentHTML('beforeend',`<option>${t}</option>`));
const today=new Date();date.min=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().split('T')[0];
function preview(){const vals=[service.value,barber.value,date.value,time.value];const p=$('#preview');if(!vals.some(Boolean)){p.innerHTML='<p>Select your service and appointment details to see a summary here.</p>';return}const niceDate=date.value?new Date(date.value+'T12:00:00').toLocaleDateString('en-ZA',{weekday:'short',day:'numeric',month:'long',year:'numeric'}):'—';p.innerHTML=`<div class="summary-line"><span>Service</span><b>${service.value||'—'}</b></div><div class="summary-line"><span>Barber</span><b>${barber.value||'—'}</b></div><div class="summary-line"><span>Date</span><b>${niceDate}</b></div><div class="summary-line"><span>Time</span><b>${time.value||'—'}</b></div><div class="summary-line"><span>Price</span><b>${service.value?'R'+prices[service.value]:'—'}</b></div>`}
[service,barber,date,time].forEach(x=>x.addEventListener('change',preview));
$$('.service-book').forEach(b=>b.addEventListener('click',()=>{service.value=b.dataset.service;preview();document.querySelector('#booking').scrollIntoView({behavior:'smooth'});service.focus()}));
function localDateTime(dateStr,timeStr){return new Date(`${dateStr}T${timeStr}:00`)}
function fmtICS(d){const p=n=>String(n).padStart(2,'0');return d.getFullYear()+p(d.getMonth()+1)+p(d.getDate())+'T'+p(d.getHours())+p(d.getMinutes())+'00'}
function googleUrl(start,end,details){const q=new URLSearchParams({action:'TEMPLATE',text:`${details.service} at Vululamo Crowns`,dates:`${fmtICS(start)}/${fmtICS(end)}`,details:`Barber: ${details.barber}\nCustomer: ${details.name}\nPhone: ${details.phone}\nBooking reference: ${details.ref}`,location:'53 Juta Street, Braamfontein, Johannesburg'});return 'https://calendar.google.com/calendar/render?'+q.toString()}
function downloadICS(start,end,d){const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Vululamo Crowns//Booking//EN','BEGIN:VEVENT',`UID:${d.ref}@vululamocrowns.co.za`,`DTSTAMP:${fmtICS(new Date())}`,`DTSTART:${fmtICS(start)}`,`DTEND:${fmtICS(end)}`,`SUMMARY:${d.service} at Vululamo Crowns`,`DESCRIPTION:Barber: ${d.barber}\\nCustomer: ${d.name}\\nPhone: ${d.phone}\\nBooking reference: ${d.ref}`,'LOCATION:53 Juta Street, Braamfontein, Johannesburg','END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([body],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vululamo-crowns-appointment.ics';a.click();URL.revokeObjectURL(a.href)}
$('#bookingForm').addEventListener('submit',e=>{e.preventDefault();const start=localDateTime(date.value,time.value),end=new Date(start.getTime()+45*60000);const d={service:service.value,barber:barber.value,name:name.value,phone:phone.value,email:email.value,ref:'CB-'+Math.random().toString(36).slice(2,8).toUpperCase()};localStorage.setItem('lastBooking',JSON.stringify(d));$('#confirmationDetails').innerHTML=`<p><strong>${d.service}</strong> with ${d.barber}<br>${start.toLocaleDateString('en-ZA',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} at ${time.value}<br>Booking reference: <strong>${d.ref}</strong></p><p>A confirmation has been prepared for ${d.email}.</p>`;$('#googleCalendar').href=googleUrl(start,end,d);$('#appleCalendar').onclick=()=>downloadICS(start,end,d);openModal(confirmation)});
$('#closeConfirmation').addEventListener('click',()=>closeModal(confirmation));
</script>
